### PR TITLE
Added 'onLaunch' event

### PR DESCRIPTION
**Pull request by jslootweg**
I like your library but I wanted an event when the menu was launched, to do some pre-launch processing.  So I have added the event.

### CODE REVIEW

**Comment by jslootweg** [comment]
I have also added the ability to disable items on the menu and added some example CSS for disabled items.

**Comment by pontikis** [comment]
Thank you for your contribution. I am out of the office for a few days. Ι will settle the changes you made ASAP.

**Comment by horus68** [comment]
@pontikis any updates on this?

**Comment by pontikis** [comment]
@horus68 As you can see the project is not updated since 2014. Unfortunately, I have not the time. However, thank you for your interest.

**Pull request closed without merging**
